# Accessing Elements in NumPy Arrays

This lesson covers:

* Accessing specific elements in NumPy arrays

Accessing elements in an array or a DataFrame is a common task. To begin this lesson, clear the
workspace set up some vectors and a $5\times5$ array. These vectors and matrix will make it easy
to determine which elements are selected by a command.


Using `arange` and `reshape` to create 3 arrays:

* 5-by-5 array `x` containing the values 0,1,...,24 
* 5-element, 1-dimensional array `y` containing 0,1,...,4
* 5-by-1 array `z` containing 0,1,...,4


In [1]:
import numpy as np

x = np.arange(25).reshape((5, 5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [2]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [3]:
# The -1 tells numpy to automatically compute the size of
# the dimension using the remaining elements, in this case, 5
z = np.arange(5).reshape((-1, 1))
z

array([[0],
       [1],
       [2],
       [3],
       [4]])

## Zero-based indexing
Python indexing is 0 based so that the first element has position `0`, the second has position `1`
and so on until the last element has position `n-1` in an array that contains `n` elements in
total.

## Problem: Scalar selection
Select the number 2 in all three, `x`, `y`, and `z`.


**Question**:  Which index is rows and which index is columns?

In [4]:
x[0, 2]

2

In [5]:
y[2]

2

In [6]:
z[2, 0]

2

## Problem: Scalar selection of a single row

Select the 2nd row in `x` and `z` using a single integer value.
 
**Question**: What is the dimension of `x` and the second row of `x`

In [7]:
x[1]

array([5, 6, 7, 8, 9])

In [8]:
print(f"Dimension of x[2]: {x[1].ndim}")

Dimension of x[2]: 1


In [9]:
z[1]

array([1])

In [10]:
print(f"Dimension of z[2]: {z[1].ndim}")

Dimension of z[2]: 1


## Problem: Slice selection of a single row

Use a slice to select the 2nd row of `x` and the 2nd element of `y` and `z`.

**Question**: What are the dimension selections?

In [11]:
x[1:2]

array([[5, 6, 7, 8, 9]])

In [12]:
y[1:2]

array([1])

In [13]:
z[1:2]

array([[1]])

## Problem: List selection of a single row

Use a list to select the 2nd row of `x` and the 2nd element of `y` and `z`.

**Question**: What are the dimension selections?

In [14]:
x[[1]]

array([[5, 6, 7, 8, 9]])

In [15]:
y[[1]]

array([1])

In [16]:
z[[1]]

array([[1]])

## Problem: Selecting a single Column
Select the 2nd column of x using a scalar integer, a slice and a list.

**Question**: What the the dimensions of the selected elements?

In [17]:
print(x[:, 1])

[ 1  6 11 16 21]


In [18]:
print(x[:, [1]])
print(x[:, 1:2])

[[ 1]
 [ 6]
 [11]
 [16]
 [21]]
[[ 1]
 [ 6]
 [11]
 [16]
 [21]]


## Problem: Selecting a block of specific columns
Select the 2nd and 3rd columns of x using a slice.

In [19]:
print(x[:, 1:3])

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]

## Problem: Selecting a block of specific rows
Select the 2nd and 4th rows of x using both a slice and a list. 


In [20]:
print(x[[1, 3], :])
print(x[1:4:2, :])

[[ 5  6  7  8  9]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]


## Problem: Selecting a block of specific rows and columns
Combine these be combined to select the 2nd and 3rd columns and 2nd and 4th rows.

In [21]:
print(x[1:4:2, 1:3])

# Right
print(x[[1, 3], 1:3])

# Also Right
print(x[1:4:2, [1, 2]])

[[ 6  7]
 [16 17]]


[[ 6  7]
 [16 17]]
[[ 6  7]
 [16 17]]


In [22]:
# Wrong
print("Looks right, but wrong!!")
print(x[[1, 3], [1, 2]])

Looks right, but wrong!!
[ 6 17]


## Problem: Use `ix_` to select rows and columns using lists
Use `ix_` to select the 2nd and 4th rows and 1st and 3rd columns of `x`.

In [23]:
# Must use ix_ when both selectors are "fancy" to get blocks
x[np.ix_([1, 3], [1, 2])]

array([[ 6,  7],
       [16, 17]])

In [24]:
# Also correct, but hard to get right
x[[[1, 1], [3, 3]], [[1, 2], [1, 2]]]

array([[ 6,  7],
       [16, 17]])

## Problem: Convert a DataFrame to a NumPy array

Use  `.to_numpy` to convert a DataFrame to a NumPy array.

In [25]:
# Setup: Create a DataFrame
import numpy as np
import pandas as pd

names = ["a", "b", "c", "d", "e"]
x = np.arange(25).reshape((5, 5))
x_df = pd.DataFrame(x, index=names, columns=names)
print(x_df)

    a   b   c   d   e
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24


In [26]:
x_np = x_df.to_numpy()
print(x_np)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Problem: Use `np.asarray` to convert to an array

Use  `np.asarray` to convert a DataFrame to a NumPy array.

In [27]:
x_np = np.asarray(x_df)
print(x_np)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Exercises

### Exercise: Block selection

Select the second and third rows of `a` and the first and last column.
Use at least three different methods including all slices, `np.ix_`, and
mixed slice-list selection.

In [28]:
# Setup: Data for Exercises

import numpy as np

rs = np.random.RandomState(20000214)
a = rs.randint(1, 10, (4, 3))
b = rs.randint(1, 10, (6, 4))

print(f"a = \n {a}")
print()
print(f"b = \n {b}")

a = 
 [[8 3 9]
 [3 8 6]
 [4 9 9]
 [2 1 1]]

b = 
 [[5 2 4 2]
 [7 1 2 3]
 [1 2 2 4]
 [3 2 1 4]
 [7 3 2 9]
 [1 2 1 3]]


In [29]:
a[np.ix_([1, 2], [0, 2])]

array([[3, 6],
       [4, 9]])

In [30]:
a[1:3, 0:3:2]

array([[3, 6],
       [4, 9]])

In [31]:
a[1:3, [0, 2]]

array([[3, 6],
       [4, 9]])

### Exercise: Row Assign

Assign the first three elements of the first row of `b` to `a`.

**Note** Assignment sets one selected block in one array equal to another 
block.

```python
x[0:2,0:3] = y[1:3,1:4]
```

In [32]:
a[0] = b[0, :3]
a

array([[5, 2, 4],
       [3, 8, 6],
       [4, 9, 9],
       [2, 1, 1]])

### Exercise: Block Assign

Assign the block consisting the first and third columns and the second and last rows of `b`
to the last two rows and last two columns of `a`

In [33]:
a[-2:, -2:] = b[np.ix_([1, 5], [0, 2])]
a

array([[5, 2, 4],
       [3, 8, 6],
       [4, 7, 2],
       [2, 1, 1]])